apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-new
spec:
  selector:
    matchLabels:
      app: nginx-new
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx-new
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 443
